
/* HISTORY ACTIONS */
export const FETCH_HISTORY_START = 'FETCH_HISTORY_START';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE';

/* ADD POINTS ACTIONS */
export const ADD_POINTS_START = 'FETCH_POINTS_START';
export const ADD_POINTS_SUCCESS = 'FETCH_POINTS_SUCCESS';
export const ADD_POINTS_FAILURE = 'FETCH_POINTS_FAILURE';
export const ADD_POINTS_RESTART_SUCCESS = 'FETCH_POINTS_RESTART_SUCCESS';
export const ADD_POINTS_RESTART_FAILURE = 'FETCH_POINTS_RESTART_FAILURE';

/* FETCH PRODUCTS ACTIONS */
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

/* REDEEM PRODUCTS ACTIONS */
export const REDEEM_PRODUCTS_START = 'REDEEM_PRODUCTS_START';
export const REDEEM_PRODUCTS_SUCCESS = 'REDEEM_PRODUCTS_SUCCESS';
export const REDEEM_PRODUCTS_FAILURE = 'REDEEM_PRODUCTS_FAILURE';
export const REDEEM_PRODUCTS_RESTART_SUCCESS = 'REDEEM_PRODUCTS_RESTART_SUCCESS';

/* GET USER ACTIONS */
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

/* FILTER */
export const APPLY_FILTER = 'APPLY_FILTER';
export const SET_CATEGORY = 'SET_CATEGORY';
export const RESET_FILTER = 'RESET_FILTER'